### ISSUE TITLE
v800_downloader.sh failed

### ISSUE THREAD

**Issue by p-val** [profanum429/v800_downloader#30]
When trying to install, the script above fails on line 12.
What should "$@" expand to normally?
-----------------------------------------------------------------------------------------------------
                                  
![image](https://user-images.githubusercontent.com/2965113/38750611-c7d6e0d4-3f55-11e8-9be8-a7da2fdebc6e.png)
                                                                                                        
-----------------------------------------------------------------------------------------------------
tnx for any help!
Peter

**Comment by pcolby** [comment]
Hi @p-val,

In Bash, `$@` expands to all the arguments passed to the function / script. eg, if you run

```
./v800_downloader.sh abc 123
```

Then `$@` expands to `abc` and `123`, so that fact this its empty in your case is normal.

From the image above, the script actually failed at line 2, its just that it doesn't detect the error and stop there.

As far as I can tell (I'm not the author of this project, it just borrows a lot of code from one of my projects), this script is only used to set the LD path once the v800_downloader is installed... you probably don't need to be using it.

Did you install v800_downloader from a `deb` file, or build from source?

If you installed from `deb`, you'll need to run the script from the original install location (the script is not built to handle moving / symlinking to new locations).

If you built it locally, just run the compiled binary directly from the build directory, eg:

```./release/v800_downloader```

Cheers.

**Comment by p-val** [comment]
Hi Paul,
thank you for the assistance - it's working now!
Downloaded the wrong package :(
The bug is stil there, but understanding the purpose of the script I symlinked the libraries and set the LD_LIBRARY_PATH manually.
Note: I had to get it working before I am buying a POLAR-watch! And **Thank You** for writing bipolar - the only way to do a direct download :)

Greetings to DownUnder
Peter
